# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a49ea89721eca5ecc9e662322d866d9dd7eda27b21cac90f5dabd92b60a5a5a3ae0e587314e291e80d9d311014ee18bd39b0e6fa456b16b6c4b802bb00b4fa6

test:
  secret_key_base: e8d15473ed4bfb1bb4552f30ca4bed190fa48990b61580cd58836e9695905923becabad912b779923ff653f6cf721c33b79b8710c4d6b40bcf5641976733d71c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
